In [1]:
import numpy as np

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [11]:
import numpy as np

vector = np.random.uniform(0, 1, 10)
print("Завдання 1: Випадковий вектор (uniform, 10 елементів)")
print(vector1)
print("Shape:", vector1.shape)

Завдання 1: Випадковий вектор (uniform, 10 елементів)
[0.51598332 0.57013527 0.39699913 0.58299747 0.14561976 0.27433757
 0.07490424 0.09407936 0.02201049 0.37475087]
Shape: (10,)


In [12]:
vector2 = np.random.rand(10)
print("Завдання 2: Випадковий вектор (rand, 10 елементів)")
print(vector2)
print("Shape:", vector2.shape)

matrix = np.array([
    [11, 14, 17],
    [20, 23, 26],
    [29, 32, 35]
])

Завдання 2: Випадковий вектор (rand, 10 елементів)
[0.82880126 0.07302446 0.62789382 0.28288506 0.50940218 0.21836722
 0.19189669 0.95065662 0.40518416 0.84281886]
Shape: (10,)


In [13]:
print("\n Завдання 3: Матриця 3x3 з фіксованими значеннями")
print(matrix)
print("Shape:", matrix.shape)


 Завдання 3: Матриця 3x3 з фіксованими значеннями
[[11 14 17]
 [20 23 26]
 [29 32 35]]
Shape: (3, 3)


In [14]:
identity_matrix = np.eye(4)
print("\n Завдання 4: Одинична матриця 4x4")
print(identity_matrix)
print("Shape:", identity_matrix.shape)


 Завдання 4: Одинична матриця 4x4
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Shape: (4, 4)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [15]:
vector_plus_10 = np.round(vector + 10, 2)
print("Вектор +10 та округлення до 2 знаків:")
print(vector_plus_10)

Вектор +10 та округлення до 2 знаків:
[10.83 10.59 10.76 10.63 10.87 10.98 10.21 10.6  10.92 10.2 ]


In [18]:
matrix_times_2 = matrix * 2
print("Матриця, помножена на 2:")
print(matrix_times_2)

Матриця, помножена на 2:
[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [19]:
vector_squared = vector ** 2
print("Квадрати елементів вектора:")
print(vector_squared)

Квадрати елементів вектора:
[0.69136867 0.34314275 0.58287285 0.39139024 0.75971612 0.96368692
 0.04573052 0.36261707 0.85449598 0.03958144]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [28]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [24]:
result_matrix = B @ A
print("Result matrix (B × A):")
print(result_matrix)
print("Shape:", result_matrix.shape)

Result matrix (B × A):
[[0.7281 0.5202]
 [0.2034 0.2846]]
Shape: (2, 2)


In [26]:
result_vector = result_matrix @ C
print("result_matrix × C:")
print(result_vector)
print("Shape:", result_vector.shape)

result_matrix × C:
[[0.5202]
 [0.2846]]
Shape: (2, 1)


In [27]:
result_matrix_D = result_matrix @ D
print("result_matrix × D:")
print(result_matrix_D)
print("Shape:", result_matrix_D.shape)

result_matrix × D:
[[0.5202 0.7281]
 [0.2846 0.2034]]
Shape: (2, 2)



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [31]:
result_matrix_transposed = result_matrix.T

print(result_matrix_transposed)

[[0.7281 0.2034]
 [0.5202 0.2846]]


In [35]:
transposed_vector = vector.T

print("Форма vector:", vector.shape)
print("Форма transposed_vector:", transposed_vector.shape)

Форма vector: (10,)
Форма transposed_vector: (10,)


Нічого не змінюється, тому що vector не має окремих осей для "рядків" і "стовпців"

In [37]:
column_vector = np.expand_dims(vector, axis=1)

print("Вихідний вектор (vector):")
print(vector)
print("Форма:", vector.shape)

print("\nСтовпчиковий вектор (column_vector) після expand_dims:")
print(column_vector)
print("Форма:", column_vector.shape)

Вихідний вектор (vector):
[0.83148582 0.58578387 0.7634611  0.62561189 0.87161696 0.98167557
 0.21384696 0.60217694 0.92438952 0.19895085]
Форма: (10,)

Стовпчиковий вектор (column_vector) після expand_dims:
[[0.83148582]
 [0.58578387]
 [0.7634611 ]
 [0.62561189]
 [0.87161696]
 [0.98167557]
 [0.21384696]
 [0.60217694]
 [0.92438952]
 [0.19895085]]
Форма: (10, 1)


In [38]:
transposed_column_vector = column_vector.T

print("Стовпчиковий вектор (column_vector):")
print(column_vector)
print("Форма:", column_vector.shape)

print("\nТранспонований вектор (transposed_column_vector):")
print(transposed_column_vector)
print("Форма:", transposed_column_vector.shape)

Стовпчиковий вектор (column_vector):
[[0.83148582]
 [0.58578387]
 [0.7634611 ]
 [0.62561189]
 [0.87161696]
 [0.98167557]
 [0.21384696]
 [0.60217694]
 [0.92438952]
 [0.19895085]]
Форма: (10, 1)

Транспонований вектор (transposed_column_vector):
[[0.83148582 0.58578387 0.7634611  0.62561189 0.87161696 0.98167557
  0.21384696 0.60217694 0.92438952 0.19895085]]
Форма: (1, 10)
